use_frameworks!

platform :ios, '9.0'

target 'KKTableCollectionViewDataSource_Example' do
  pod 'KKTableCollectionViewDataSource', :path => '../'

  target 'KKTableCollectionViewDataSource_Tests' do
    inherit! :search_paths

    
  end
end
